### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Negi-Ashish** [statichunt/hydrogen-nextjs#1]
I have cloned the repo,

![image](https://user-images.githubusercontent.com/67871153/211190487-a6fe6091-f1b9-4db3-8bad-65330323502f.png)

Facing a error with the existing import, project is not able to start properly thanks.

![image](https://user-images.githubusercontent.com/67871153/211190530-bd40490e-0fbb-4344-9231-37107de768ed.png)

Thanks for your time and help.

**Comment by tfsomrat** [comment]
Please first run `npm run build` then run `npm run dev`
